### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by thenameissasi** [zachysaur/roop-unleased-kaggle#3]
kaggle automatically disconnects after starting the webserver

**Comment by zachysaur** [comment]
did it generated gradio url?

**Comment by thenameissasi** [comment]
yes. it disconnects immediately after generating url.

same with facefusion

**Comment by zachysaur** [comment]
kaggle dont support gradio

**Comment by thenameissasi** [comment]
used to work. what to do now? tried cli mode by with -t -s and -o options and all other optons specified while running, but it attempts to start gradio and disconnects.

**Comment by zachysaur** [comment]
i will make a new notebook
